### ISSUE TITLE
Entity Retweet % Incorrect in main_stats.dat

### ISSUE THREAD

**Issue by nbuhagiar** [hashkat/hashkat#10]
When referencing the main_stats.dat file in the output directory after running a simulation that allows retweets, the number and percentage of retweets which were done  by each entity type is listed under the total number of retweets under the "Retweets" heading. However, this percentage is off by two decimal places. In the attached example, with 'Standard' entities retweeting 12 times and 'Celebritiy' entities retweeeting 26 times out of 38 total retweets, their percentage out of the total number of retweets is 0.315789% and 0.684211% respectively as opposed to the correct values of 31.5789% and 68.4211% respectively.

![retweet_percentage_image](https://cloud.githubusercontent.com/assets/10453145/8091007/0c414570-0f7f-11e5-8944-8fbca2bbae88.png)

**Comment by kryczko** [comment]
I have changed the source code so this should no longer be an issue.
