### ISSUE TITLE
How should LANG output array be interpreted

### ISSUE THREAD

**Issue by lkettle** [hashkat/hashkat#103]
Language results are reported by array number {0,1,2,3}

How should the array be interpreted:  by order in config_static,h or by order in hashkat_pre.py?

![config_langs](https://cloud.githubusercontent.com/assets/14791604/12894264/ba19dfba-ce63-11e5-8d44-7bea4d0c537c.png)
![langs_hk_pre_py](https://cloud.githubusercontent.com/assets/14791604/12894285/cdfd94cc-ce63-11e5-9265-958c716bcf9c.png)

**Comment by lkettle** [comment]
hashkat_pre.py language order to match config_static.h

**Comment by ludamad** [comment]
Yes you have caught a bug here. This order should match.

**Comment by lkettle** [comment]
I changed hashkat_pre.py to match
