### ISSUE TITLE
RETWEET:  Not Retweeting Tweets with Hashtags

### ISSUE THREAD

**Issue by lkettle** [hashkat/hashkat#110]
I did an n=53 study with 20% of tweets supposed to be created with Hashtags.
Most Popular Tweet generated 49 times.  0% of the time did the MPT contain a Hashtag.

I just did an n=12 study with 10% of tweets supposed to be created with Hashtags.
Most Popular Tweet generated 12 times.  0% of the time did the MPT contain a Hashtag.

Total 61 runs, 0% with hashtags.

I'm thinking Hashtagged tweets are NOT being retweeted.

![mpt_n53](https://cloud.githubusercontent.com/assets/14791604/13192779/bd3daa9a-d73d-11e5-88d5-172143eb8c1e.png)

![region_retweet](https://cloud.githubusercontent.com/assets/14791604/13192770/a1c2f7de-d73d-11e5-9cdb-9989c47f4baf.png)

**Comment by lkettle** [comment]
I ran the default INFILE with 100% of tweets having #hashtags p = 1.0 (
[INFILE_retweets_w_hashtags.yaml.zip](https://github.com/hashkat/hashkat/files/145771/INFILE_retweets_w_hashtags.yaml.zip)
and follow via retweet enabled) for 5 minutes and I DID have retweets.

**Comment by lkettle** [comment]
Well I'm confused, because this INFILE with 100% hashtags does not generate any 

retweets.

**Comment by lkettle** [comment]
[INFILE_hashkats_p1_no_retweets.yaml.zip](https://github.com/hashkat/hashkat/files/185349/INFILE_hashkats_p1_no_retweets.yaml.zip)

**Comment by lkettle** [comment]
I mean "hashtags"

**Comment by lkettle** [comment]
[INFILE_hashtags_p1_no_retweets.yaml.zip](https://github.com/hashkat/hashkat/files/185350/INFILE_hashtags_p1_no_retweets.yaml.zip)

**Comment by ludamad** [comment]
I have investigated, your INFILE_hashtags_p1_no_retweets.yaml.zip does not seem to generate retweets with p=0 or p=1. Increasing the amount of time causes retweets to appear in both cases. Perhaps this is a bug with the way the most popular tweet is calculated.

**Comment by ludamad** [comment]
Investigated the proportions of tweets with hashtags with p=0.5 and supposedly overlapping languages:

Run 1
LANG_ENGLISH: 3362
TWEET_STANDARD: 833
with_hashtag: 621
Region0: 3362
TWEET_HUMOUROUS: 841
TWEET_IDEOLOGICAL: 841
without_hashtag: 2741
TWEET_MUSICAL: 847

Run 2
LANG_ENGLISH: 3451
TWEET_STANDARD: 860
TWEET_HUMOUROUS: 827
with_hashtag: 686
Region0: 3451
TWEET_MUSICAL: 894
TWEET_IDEOLOGICAL: 870
without_hashtag: 2765

Re-opening as hashtags do seem to be under-represented. To investigate further.
