### ISSUE TITLE
[documentation] Replace (tm) with proper Trademark (™)symbol

### ISSUE THREAD

**Issue by jig08** [hashkat/hashkat#117]
The first line under the heading **What is Hashkat?** in [Quick Start](https://github.com/hashkat/hashkat/blob/master/docs/quickstart.md) reads as _"...#k@ simulates an online social network such as Twitter(tm)...."_
Replace `(tm)` with proper Trademark `™` symbol.

**Comment by lkettle** [comment]
Please feel free to amend any documentation you want.  Neither Nick nor I are currently on salary.
Seems a waste to assign a bug when it can be changed in same amount of time.

**Comment by lkettle** [comment]
I've tried using &trade and it doesn't work, so left it as is "Twitter(tm)" which is legally sufficient.  If you can figure it out, please feel free to change.

**Comment by jig08** [comment]
@lkettle Oh, sorry. Did not know that.
