### ISSUE TITLE
[documentation] Erroneous formatting in Quick Start

### ISSUE THREAD

**Issue by jig08** [hashkat/hashkat#119]
In the [Quick Start](http://docs.hashkat.org/en/latest/quickstart/) documentation, the code snippet after the line _"In Python, use Networkx to create a plot of your network: .."_ has erroneous formatting. 

Each line is ending with a **" ` "** which should not be the case.

![screenshot from 2016-06-03 16 24 07](https://cloud.githubusercontent.com/assets/9291400/15791630/73fc4d1c-29a6-11e6-8468-090add1a64de.png)

**Comment by lkettle** [comment]
Please feel free to amend any documentation you want.
Seems a waste to create a ticket for something that can be changed in same amount of time.

**Comment by lkettle** [comment]
As I recall this was a cut & paste from the visualization tutorial, and there was some wackiness that had to do with markdown formatting.  Feel free to fix.

**Comment by lkettle** [comment]
OK fixed
