### ISSUE TITLE
Currently No Control Over the Output of Several Files

### ISSUE THREAD

**Issue by nbuhagiar** [hashkat/hashkat#12]
There seems to be no variable in INFILE.yaml to allow or prevent the following files from being outputted to the output directory:

connections_vs_nodes.dat
dd_by_entity_type.dat
dd_by_follow_model.dat

Are we going to add a variable to allow users of hashkat to have control over this, or leave it as is?

**Comment by kryczko** [comment]
I have fixed this issue by creating a yaml input variable for dd_by_follow_model, and have removed dd_by_entity_type because this is already being done with entity_stats. I have also removed connections_vs_nodes.
