### ISSUE TITLE
[documentation] Improper link to L. Kettle's profile

### ISSUE THREAD

**Issue by jig08** [hashkat/hashkat#120]
In the [About Hashkat](http://docs.hashkat.org/en/latest/about/) section, there is an improper link format to `L. Kettle`'s profile in the last line.

Refer screenshot attached.

![screenshot from 2016-06-03 16 44 51](https://cloud.githubusercontent.com/assets/9291400/15792155/78f525ac-29a9-11e6-8ceb-48d869456209.png)

**Comment by lkettle** [comment]
Fixed
