### ISSUE TITLE
Entities Should be Renamed to Agents

### ISSUE THREAD

**Issue by nbuhagiar** [hashkat/hashkat#13]
To coincide with the "Agent-based simulation of complex social networks, a kinetic Monte Carlo approach" paper, 'entities' need to be renamed to 'agents' in the hashkat program. With this in mind, the 'initial entities' and 'max entities' should be changed to 'initial agents' and 'max agents' respectively, the 'entity' follow model and 'preferential entity' follow model should be probably renamed to the 'agent' follow model and 'preferential agent' follow model respectively, the 'entity stats' output files should be the 'agent stats' output files, and the 'entity types' will naturally become the 'agent types'.

**Comment by ludamad** [comment]
Agreed. I forsee no problems with a mass text replacement 'entities -> agents' and 'entity -> agent'.

**Comment by ludamad** [comment]
Noting here that there are a few 'Identity' -> 'Idagent' cases, will have to look for cases where there is a character before 'agent' to clean that up.

**Comment by itamblyn** [comment]
Wouldn't a subsequent

Idagent -> agent

solve this?

- Isaac

**Comment by ludamad** [comment]
Uh yes that was a personal reminder, already done
