### ISSUE TITLE
Too Many Retweets

### ISSUE THREAD

**Issue by nbuhagiar** [hashkat/hashkat#155]
Thought I posted this earlier, but I once ran a few simulations consisting of only 3 agents. each making a tweet per minute, with a tweet transmission prob of 1, for 100,000 simulated minutes. I would have expected there to be 6 retweets per minute, but running a simulation for 100,000 minutes
gave me a total of just over 700,000 retweets on average for several different seeds.

This might be due to agents retweeting there own tweets, or perhaps due to agents retweeting both the retweet of a tweet, and the original tweet itself, resulting in an agent retweeting the same tweet twice.

This is probably worth looking into to.

**Comment by itamblyn** [comment]
Thanks Nick

- Isaac
