### ISSUE TITLE
Unable to Run #k@ Outside Directory

### ISSUE THREAD

**Issue by nbuhagiar** [hashkat/hashkat#166]
Hey,

It's been quite some time since I used #k@, but I remember being able to run hashkat wherever on my computer as long as the current working directory had an INFILE.yaml in it. I have git cloned the repo on to my computer and get an error when attempting this. Is there an additional step that needs to be done to  achieve this?

Thanks

**Comment by ludamad** [comment]
This was broken a bunch of commits ago, sorry. It should be working now. Can you verify?

**Comment by nbuhagiar** [comment]
Yep, it's working great! Thanks a lot!
