### ISSUE TITLE
bilingualism

### ISSUE THREAD

**Issue by kryczko** [hashkat/hashkat#176]
As far as I know, bilingualism does not work properly. Could this please be implemented in the handle_follow function. I'm not sure where the Language class is, and I'm not sure how the compare would work for the case of bilingualism.

**Comment by ludamad** [comment]
Can you elaborate, what should bilingualism be doing that it isn't right now?

**Comment by kryczko** [comment]
Well, right now, agents only connect if they speak the same language. So if agent A speaks language Y and agent B speaks language Y and Z, will the agents be able to connect if we compare A.language to B.language?

The same rules should apply for retweeting.

**Comment by ludamad** [comment]
I have fixed the issue and pushed it with a test so it doesn't recur. Thanks!
