### ISSUE TITLE
Presence of Connections between Regions Chart in Display

### ISSUE THREAD

**Issue by nbuhagiar** [hashkat/hashkat#18]
Just a question with regards to the connections between regions chart that used to display to the screen when running a simulation. This hasn't been appearing to the screen when running the simulation for some time. Has this been removed from the program, or is something wrong and this needs to be fixed and returned to the display? If you're unsure which chart I am referring to, it looks like the following image:

![connections_between_regions_chart_image](https://cloud.githubusercontent.com/assets/10453145/8208707/0d6b646e-14d7-11e5-8154-453f36d63dad.png)

**Comment by ludamad** [comment]
Recently this was made to update information on the same line without an option to toggle it. I'd be in favour of making the default like it use to be, the new default is less informative.

**Comment by nbuhagiar** [comment]
I personally prefer the old format with the chart present as well, but it's
up to you two

**Comment by ludamad** [comment]
Oh wait, I might not understand what you were referring to. I thought you referring to the block that displayed stats about the network, but now updates on one line.

**Comment by nbuhagiar** [comment]
I was referring to the chart that appears when running a simulation that
shows the connections between regions. At 1:17 in this old video I made
(with the link to it below) you can see the chart appear that shows the
connections between regions 0, 1, and 2, which correspond to the regions
Ontario, Quebec, and Mexico respectively. That no longer appears when I run
a simulation.

https://www.youtube.com/watch?v=-NQmVRzHX44

**Comment by ludamad** [comment]
Alright, Kevin will have to handle that one

**Comment by nbuhagiar** [comment]
Not a problem, thanks buddy!

**Comment by kryczko** [comment]
Issue is fixed, the matrix is now in region_connection_matrix.dat in output directory.

**Comment by nbuhagiar** [comment]
Awesome! Thank you Sir
