### ISSUE TITLE
Remove obsolete tweet_observation.resolution_growth_factor

### ISSUE THREAD

**Issue by ludamad** [hashkat/hashkat#19]
A comment says its obsolete so it should just be removed.

**Comment by nbuhagiar** [comment]
Okay, I will remove it from every INFILE.yaml file

**Comment by ludamad** [comment]
Just dont do it manually, otherwise you're wasting time :) I can do it with
a find replace, I just wanted confirmation from Kevin that everything will
work without it

**Comment by nbuhagiar** [comment]
Okay, fair enough. Thanks!

**Comment by itamblyn** [comment]
@kryczko Comments?

**Comment by kryczko** [comment]
I have no idea if this is obsolete. Has testing been done to prove so?

**Comment by ludamad** [comment]
what does the comment mean then?

**Comment by ludamad** [comment]
Kevin, you added this comment in this commit: https://github.com/hashkat/hashkat/commit/b2cf6094dd2b8d8bc033cfb4ab074ab205d9df72, I'm not sure what it's referring to.

**Comment by kryczko** [comment]
I was basically trying to make it so that we wouldn’t need to compile to change some of the things in the code. Stuff in config_static. I wasn’t successful so I reverted.

**Comment by ludamad** [comment]
OK. It was a forgotten stray comment. Everyone, use the 'blame' button on github when viewing files before assuming you didn't add something :-). Moving forward now we should decide whether we don't like this growth factor, but it's not obsolete ATM.
