### ISSUE TITLE
'main_stats.dat' Output File Missing Data When 'use_barabasi' is Implemented

### ISSUE THREAD

**Issue by nbuhagiar** [hashkat/hashkat#21]
Whenever 'use_barabasi' is implemented into a network simulation, the 'Total follow attempts' and 'Preferential' follow attempts show to be zero in the 'main_stats.dat' output file, when this should definitely not be the case. A screenshot of this is shown below:

![use_barabasi_main_stats_image](https://cloud.githubusercontent.com/assets/10453145/8238383/504eae0c-15c3-11e5-9f2c-809ed9825cf7.png)

**Comment by ludamad** [comment]
This seems to be working now.
