### ISSUE TITLE
SSE2 instructions

### ISSUE THREAD

**Issue by itamblyn** [hashkat/hashkat#22]
Currently #k@ has SSE2 dependencies. This means that builds on ARM (e.g. raspberry pi) and Power PC don't work.

Building CXX object src/CMakeFiles/hashkat.dir/dependencies/mersenne-simd/SFMT.cpp.o
Building CXX object src/CMakeFiles/hashkat.dir/config_dynamic.cpp.o
In file included from /home/pi/git/hashkat/src/dependencies/mersenne-simd/SFMT.cpp:26:
In file included from /home/pi/git/hashkat/src/dependencies/mersenne-simd/SFMT.h:83:
/usr/include/clang/3.5.0/include/emmintrin.h:28:2: error: "SSE2 instruction set
      not enabled"
#error "SSE2 instruction set not enabled"

**Comment by ludamad** [comment]
Just delete those files, they aren't used

**Comment by itamblyn** [comment]
Tried deleting all files in mersenne-simd, then putting back one after another (i.e. when prompted that they were missing). I still get the error about emmintrin

**Comment by ludamad** [comment]
OK, I excised them.
