### ISSUE TITLE
'dd_by_follow_model.dat' Might Need Some Labelling

### ISSUE THREAD

**Issue by nbuhagiar** [hashkat/hashkat#33]
The 'dd_by_follow_model.dat' file contains several columns of data that are not titled or labelled. It might be a good idea to add these into the file for clarity. An image of this file's contents are shown below:

![dd_by_follow_model](https://cloud.githubusercontent.com/assets/10453145/8366051/8a82b7ca-1b5f-11e5-817d-a518510c1dfe.png)

**Comment by ludamad** [comment]
From another point of view, if you add labels this information becomes harder to read into a program (you would have to ignore the first line). There could be documentation somewhere else.

**Comment by itamblyn** [comment]
Using # at the beginning of the line is a pretty standard way of dealing
with this.

For consistency with other files, the label should be included in .dat file

- Isaac

**Comment by ludamad** [comment]
Sounds right to me

**Comment by nbuhagiar** [comment]
I've labelled the dd_by_follow_model file. Judging by its data, for every degree it outputs the ln of its value and  the normalized probability and the ln of that value for every follow method used except following via retweets. The twitter follow model is also treated as another follow method instead of a combination of several methods. When running a twtter follow model simulation, it outputs the normalized probability and ln of the normalized probability for connections made via the twitter follow method specifically. It does not seem to differentiate the different follow methods used within the twitter follow model. Are we okay with this?

An image of the dd_by_follow_model out file for a twitter simulation with all follow models evenly weighted is shown below:

![twitter_dd_image](https://cloud.githubusercontent.com/assets/10453145/8603211/d5f8ecca-2644-11e5-97ac-d50982bb732e.png)

**Comment by kryczko** [comment]
Looks good Nick, good work!

Kevin

**Comment by nbuhagiar** [comment]
Thanks Kevin!
