### ISSUE TITLE
Retweet Visualization Check

### ISSUE THREAD

**Issue by nbuhagiar** [hashkat/hashkat#36]
Just a reminder to look into how 'retweets_viz.gexf' works, and how it can possibly be modified to show the most popular tweet in a network simulation

**Comment by kryczko** [comment]
This should be working properly, I investigated the code. When this is turned on, it finds the tweet that has been retweeted the most and saves the tweet data structure in memory. Once the simulation finishes, the original tweeter, the retweeters, and non-retweeters are written to disk and can be read into Gephi. The nodes written to disk are:

- the original tweeter as well as the followers of the original tweeter
- the retweeters as well as the followers of the retweeters

This was done to check and make sure retweets were occurring naturally.

NOTE: This will slow down simulation times and should not be used when generating large networks.
