### ISSUE TITLE
Error after Analysis Completes

### ISSUE THREAD

**Issue by nbuhagiar** [hashkat/hashkat#38]
When running a hashkat, I sometimes get the following error:

"
Simulation Completed: desired simulation time reached

Creating analysis files -- press ctrl-c multiple times to abort ... 
Analysis complete!
**\* Error in `/home/mobile/hashkat/build/src/hashkat': double free or corruption (!prev): 0x0000000014b23880 ***
/home/mobile/hashkat/hashkat.sh: line 80:  6097 Aborted                 (core dumped) "$HASHKAT/build/src/hashkat" $args
"

Oddly enough, I can run a network simulation, and there could be no errors, but if I then increase the agent follow ranks I get an error.

Any idea what could be the cause of this?

**Comment by ludamad** [comment]
This should be run through a debugger. If you are increasing something, you could be hitting a hardcoded limit. Not sure.

**Comment by itamblyn** [comment]
Ok, more on this. The offending file is here: tests/referencefiles/test02/INFILE.yaml

It works fine on OS X, but has trouble with linux.

**Comment by nbuhagiar** [comment]
Just a note about this issue. it is found in tests/referencefiles/test99/. I have not received the above error message since, but I do receive an error message similar to the one below on Linux, though it works fine on Mac OS X:

'
Analysis complete!
/home/mobile/hashkat/run.sh: line 92:  4485 Segmentation fault      (core dumped) "$HASHKAT/build/src/hashkat" $args
'
