### ISSUE TITLE
Boost.Test implementation of the test set

### ISSUE THREAD

**Issue by arminms** [hashkat/hashkat#41]
As part of the extensive refactoring, Boost.Test implementation of the test set is necessary for lean and mean testings.

**Comment by ludamad** [comment]
Why Boost.Test? I don't see anything wrong with UnitTest++ that we already use.

**Comment by ludamad** [comment]
Looking at Boost.Test, it is almost identical to UnitTest++, except UnitTest++ is an isolated dependency. My only really gripe with Boost is that it's really hard to separate the components, and given that we bundle source for convenience, this can be nice to do.

**Comment by arminms** [comment]
The test.cpp using Boost.Test is ready and completely functional. Just try to write the same program with the same functionality using UnitTest++ and let's see which one is shorter! ;) I've also included the CMakeLists.txt file to build it automatically by CMake. You can see the complete program options by running ./test --help. In short, some useful flags are summarized below:

./test -p (shows progress bar)
./test test03 (only runs test03)

**Comment by ludamad** [comment]
Syntactically, the libraries are nearly identical.

**Comment by arminms** [comment]
After building using cmake, the binary will be in the build/tests/test folder. It is possible to run the test program from any directory. The down side of this feature is relying on HASHKAT environment variable.

**Comment by ludamad** [comment]
No worries, I'll modify so ./run.sh --test runs the tests. It defaults HASHKAT to the directory where ./run.sh is located.

**Comment by arminms** [comment]
That's great.

**Comment by ludamad** [comment]
It looks like you need to do a 'git add <path to boost>', and then commit, on your end.

**Comment by arminms** [comment]
Boost is not a library to be embedded in a project. It's something like STL. It must be take for granted that it is already installed in a system. All major Linux distributions have boost already installed, because lots of packages depend on it. And if not it can be installed easily using default package manager. On Macs, it can be installed easily using MacPorts.

**Comment by arminms** [comment]
About the name, test_hashkat seems more appropriate to me. If that sounds good to you too, I can change it.

**Comment by ludamad** [comment]
Sure, 'test_hashkat' is good. 

I understand your reservations, but I would argue that there is no real reason for it not be embedded in the project, for sake of convenience. We can always move away from this in the future, but currently, this is purely a philosophical argument, and will cause pain for the majority of our team who is non-technical. Beyond this, CMake should at least be made to correctly detect the dependency, and error if not found.

**Comment by arminms** [comment]
No problem I will put the latest version of Boost. But be aware that Boost is a really huge library. Lots of header files that prolong the initial clone from github. There is also an alternative to only include those libraries from Boost that actually needed. There is tool for doing that. What about that?

**Comment by ludamad** [comment]
Yes, I am aware Boost is a huge library :-) And yes, extracting the subsets we need seems best.

**Comment by arminms** [comment]
Sure. I've started to work on that. I'll let you know as soon as it's ready.

**Comment by arminms** [comment]
Done! I've included only Boost.Test subset. The root CMakeLists.txt was also modified to fix the broken make on systems without Boost library.

**Comment by ludamad** [comment]
Cool! Thanks Armin.
