### ISSUE TITLE
Input that controls retweet time incorrectly seems to change retweet amount

### ISSUE THREAD

**Issue by nbuhagiar** [hashkat/hashkat#43]
I've been comparing networks with different tweet observation settings and I've noticed that the 'time_span' variable seems to have no impact on the number of retweets that occur in a simulation. Is there any chance that the 'time_span' variable is what was obsolete in the stray comment previously discussed?  I've also noticed that increasing the 'x_end' value decreases the number of retweets that occur, though I would expect their number to increase since tweets would have more time to be retweeted. Is there anything I'm missing or is there an issue with 'tweet_observations'?

**Comment by ludamad** [comment]
None of those should have an impact on number of retweets; it's a probability distribution that determines the time *assuming a retweet/reaction occurs*. The transmission probability should be the only thing with an impact on retweet/reactions.

**Comment by nbuhagiar** [comment]
Okay, thanks. I misunderstood. Why did increasing the 'x_end' variable
result in a decrease in the number of retweets though?

**Comment by ludamad** [comment]
Not sure, I was partially acknowledging that might be a bug.

**Comment by nbuhagiar** [comment]
Okay. I'll leave the issue posted for now then. Thanks!

**Comment by nbuhagiar** [comment]
Further testing with 'tweet_observations' showed that manipulating any
variable in the 'tweet_observations' section except for the
'density_function' and 'time_span' resulted in a change in the number of
retweets in the simulation

**Comment by ludamad** [comment]
But was it a consistent change? If not, it is probably an artifact of the coarse logarithmic binning system, which I'm a bit dubious about right now.

**Comment by nbuhagiar** [comment]
The changes don't seem to be consistent. For some variables, increasing or
decreasing its value always decreases the total number of retweets

**Comment by ludamad** [comment]
Hm. I meant for a single variable. If increasing/decreasing a single variable is causing a strictly (plus or minus expected variation) monotonic change, that's a bit odd if its a binning artifact (but, I haven't thought about it too hard).

**Comment by itamblyn** [comment]
@nbuhagiar Can you please prepare a "controlled" test of this where we know ahead of time how many retweets to expect. Try something with a transmission prob of 1, 0.5, and 0.

**Comment by nbuhagiar** [comment]
Okay, I'll do that.

Nick

**Comment by nbuhagiar** [comment]
I've created the test files. test08, test09, and test10 have all the same
input files except for their tweet transmission rates being 0, 0.5, and 1.0
respectively. However, I noticed that even though I had the follow reaction
probability set to 0 for these tests, following via retweets was still
occurring. This relates to issue #24 I posted a few weeks ago. I have
therefore created some test files to test follow reaction prob as well.
test10, test11, and test12 have all the same input file except for their
follow_reaction_prob being 0, 0.5, and 1 respectively. test12 was
originally the test02 that wasn't working properly and has been renamed
test99.

**Comment by itamblyn** [comment]
On this point - if you think about the extremes, say observation time of 1 minute vs 100 years, in the extreme short term (1 min) limit there will be a very small number of tweets in play at any given time. The RT rate will be very high to compensate, since the total probability is conserved. In the other limit, there will be lots of tweets in play, each with much lower rates.

**Comment by ludamad** [comment]
It seems the inconsistent change is just random perturbations. Did you have a test showing otherwise? You can reopen if so. The tests I pushed in https://github.com/ludamad/hashkat/commit/f576f619b969c20fe34359284da2c4864ace689a seem to indicate that the retweet standard deviation this causes is significantly less than the normal standard deviation in differing-seed trials. Your other issue is tracked in #24.
