### ISSUE TITLE
Merges pollute the git log

### ISSUE THREAD

**Issue by ludamad** [hashkat/hashkat#45]
I only keep bringing it up because it's super easy to avoid. I will close this issue once everyone promises to use 'git pull --rebase' :-)

Or, if you don't think you'll remember / don't want to type, this will make it the default:
git config --global pull.rebase true

To elaborate, a merge represents a combination of diverged histories. On that commit, you can include a comment about how the merge was done. But, if people are editing separate files in completely different efforts, and we aren't doing merge commit messages (all of them are the default commit message) its just noise.

**Comment by itamblyn** [comment]
Right!

- Isaac

**Comment by nbuhagiar** [comment]
Haha I promise to use 'git pull --rebase'.

Nick
