### ISSUE TITLE
Quebec Region Preference Class Not Working Properly

### ISSUE THREAD

**Issue by nbuhagiar** [hashkat/hashkat#52]
The 'Quebec' region preference class seems to not work properly in the following cases:

Running a simulation with just agents from Quebec using a StandardPref with English and French speaking agents being 1:1 results in 0 retweets in the simulation.

Running another simulation with just Ontario and Quebec in the network, with Ontario having a NoRetweetPref and Quebec having a StandardPref resulted in no retweets occurring.

The Quebec preference class seems to work in other cases though. Running 2 network simulations with agents from both Ontario and Quebec, one with Ontario having a StandardPref and Quebec having a NoRetweetPref, and another where both regions have a StandardPref gave me results with differing number of retweets and following via retweets, therefore, the Quebec preference class seems to be working in that case. Running another simulation with just Quebec and Mexico present in the simulation, with Quebec having a StandardPref and Mexico having a NoRetweetPref, there were plenty of retweets and following via retweets that occurred as well.

This issue does not seem to be occur for the Ontario and Mexico regions. Any ideas on what could be the cause of this?

**Comment by itamblyn** [comment]
Inputfile?

**Comment by ludamad** [comment]
Tracked more directly by https://github.com/hashkat/hashkat/issues/104
