### ISSUE TITLE
Retweets Seem to Occur Depending on Language

### ISSUE THREAD

**Issue by nbuhagiar** [hashkat/hashkat#53]
Running three network simulation with agents in the Ontario region, one where they only speak English, one where they only speak French, and one where they only speak Spanish, I found that retweets only seemed to occur in the simulation with only English speaking agents. There were no retweets in the other simulations.

Any idea why this could be?

**Comment by itamblyn** [comment]
Can you attach an input file to this please?

Thanks

**Comment by ludamad** [comment]
Covered by #104 .
