### ISSUE TITLE
Agent Type Tweeting Even Though Tweet Rate Set to Zero and Following with Follow Rate Set to Zero

### ISSUE THREAD

**Issue by nbuhagiar** [hashkat/hashkat#54]
Running a network simulation with the following agent types:

![agent_type_tweet](https://cloud.githubusercontent.com/assets/10453145/9257956/be50f796-41c6-11e5-9e11-d568248db377.png)

gives us the following output:

![agent_type_tweet_main_stats](https://cloud.githubusercontent.com/assets/10453145/9258035/21fbbf24-41c7-11e5-99ea-676caecc2c2b.png)

As we can see, even though the Standard agent type has a tweet rate of 0.0, they created 6080 tweets in the simulation.

Any idea why this could be?

**Comment by kryczko** [comment]
Is retweeting turned on?

**Comment by nbuhagiar** [comment]
Yep

**Comment by kryczko** [comment]
Hmm, its hard to say at this point. What is the number of entity types in config_static.h?

**Comment by nbuhagiar** [comment]
The Organization-Coke and Organization-Pepsi have also made 3363 and 3459 follows respectively even though both of their follow rates are 0.0.

A screenshot of the preference class being used is shown below:

![agent_type_tweet_pref_class](https://cloud.githubusercontent.com/assets/10453145/9258406/629717de-41c9-11e5-82ee-97b405c664ca.png)

**Comment by nbuhagiar** [comment]
The number of agent types in config_static.h is 200.

**Comment by kryczko** [comment]
Is a network being preloaded in?

**Comment by nbuhagiar** [comment]
I don't understand what you mean?

**Comment by kryczko** [comment]
Like is a saved network being loaded into the code before running the simulation?

**Comment by nbuhagiar** [comment]
Nope, I've been removing the previous network_state.dat file before running the simulation

**Comment by kryczko** [comment]
Is this built with Armin’s code?

**Comment by nbuhagiar** [comment]
No, it's not.
