### ISSUE TITLE
Humour Bins Don't Seem to Affect Network

### ISSUE THREAD

**Issue by nbuhagiar** [hashkat/hashkat#55]
Running 2 network simulations that enabled retweeting with only humorous tweets, but with one having 'humour_bins: 2' and the other having 'humour_bins: 1' seemed to give me the exact same output, judging by the 'main_stats.dat' file being the same for both of them.

For 'humour_bins: 2':

![testing_humor_bins_equal_2](https://cloud.githubusercontent.com/assets/10453145/9339670/627d2678-45b9-11e5-837a-6b4d79f43fb8.png)

For 'humour_bins: 1':

![testing_humor_bins_equal_1](https://cloud.githubusercontent.com/assets/10453145/9339673/669edada-45b9-11e5-8e04-39d744c5f313.png)

Is there another way in which the humour bins impact the network that I am not seeing, or is this a bug?

**Comment by ludamad** [comment]
After digging it seems you are correct. The number of humour bins should have no effect on the network because humour is a binary trait (a tweet is either humourous or its not).

**Comment by ludamad** [comment]
Humour bins were indeed ineffectual and removed in this commit: https://github.com/hashkat/hashkat/commit/d986560bd1983dfc27c918be65fed922fc07b325

If we wish to revive the concept (which was moved away from a long time ago, but forgotten) that can be a separate issue.
