### ISSUE TITLE
Unfollow Error in Tests

### ISSUE THREAD

**Issue by nbuhagiar** [hashkat/hashkat#59]
Running a simulation using the input file in 'test01' and 'test99' in the 'tests/referencefiles' directory gives the following error:

'
FAILED CHECK: unfollow: Did not exist in follower list (/home/mobile/hashkat/src/analyzer_follow.cpp:561)
terminate called after throwing an instance of 'char const*'
../../../run.sh: line 92:  3165 Aborted                 (core dumped) "$HASHKAT/build/src/hashkat" $args
'

This error doesn't appear if I increase the 'unfollow_tweet_rate', but the 'unfollow_tweet_rate' and the agent tweet rates are the same for several other tests and I receive no error running them.

Any idea what could be the cause of this issue? It's worth noting that once this issue is fixed, the '.ref' files in the output directory for each test need to be updated.

**Comment by ludamad** [comment]
Please retry this with HEAD
