### ISSUE TITLE
Network Queries Don't Seem to Be Working

### ISSUE THREAD

**Issue by nbuhagiar** [hashkat/hashkat#60]
The network queries outlined in 'network.h' in the source code don't seem to be working.

For example, for one of these queries shown below:

FollowingSet& following_set(int id) {
    return agents[id].following_set;
}

if, after running #k@, I enter in the command 'network.following_set(1)' or 'following_set(1)' in the 'hashkat' directory, neither of these commands seem to be recognized. Is there an issue with these network queries, or am I doing something wrong?

**Comment by kryczko** [comment]
If you were trying to use this in interactive mode, I don't think this is the place to look. That code is C++, not Lua, and the network.following_set(1) can only be used when running C++.

**Comment by nbuhagiar** [comment]
I was entering these queries while in the 'hashkat' directory after running a simulation.

![network_queries_issue](https://cloud.githubusercontent.com/assets/10453145/9740247/b5bceefe-5621-11e5-8861-de0b2e15b9c2.png)

Is this not the place to enter these queries?

**Comment by kryczko** [comment]
No this needs to be within the C++ code.

**Comment by nbuhagiar** [comment]
Sorry, I don't quite understand where in the C++ code these queries can be
entered to gather info on a created network. Should I just close this
issue, since hashkat users will never be able to enter these queries from
the command line?

**Comment by ludamad** [comment]
There are two options here, either add to the part of code that writes out
analysis at the end, and simply resume the network, or use interactive
mode, binding whatever functions you need with bind_function (which allows
use interactively from terminal).
