### ISSUE TITLE
Can't Stop Simulation with a Negative Add Rate

### ISSUE THREAD

**Issue by nbuhagiar** [hashkat/hashkat#61]
Having a constant add rate that is a negative value causes the simulation to run immensely slower. Trying to stop this simulation by pressing 'Ctrl-c' seems to do nothing.

**Comment by ludamad** [comment]
This is a bug only insomuch that a negative rate anywhere should be rejected as an invalid config. Having a network where people leave is not supported

**Comment by nbuhagiar** [comment]
Okay, good to know. Thanks!

**Comment by itamblyn** [comment]
Let's open a new improvement ticket to verify the sign of input rates
