### ISSUE TITLE
Possible Number of Regions Issue

### ISSUE THREAD

**Issue by nbuhagiar** [hashkat/hashkat#65]
In #k@, no matter how many regions are in 'DEFAULT.yaml', the number of regions in 'INFILE.yaml' must match the number of regions assigned in 'config_static.h' EXACTLY.

For example, I have 'N_BIN_REGIONS' equal to 3 in 'config_static.h', and 3 regions in 'DEFAULT.yaml' but only 1 in 'INFILE.yaml'. Running #k@, I receive this error:

'
FAILED CHECK: Should match! (/home/nbuhagiar/hashkat/src/analyzer_main.cpp:281)
'

The line in question in 'analyzer_main.cpp' is:

'
DEBUG_CHECK(R.regions.size() == N_BIN_REGIONS, "Should match!");
'

Should this be remedied, or left as is?

**Comment by ludamad** [comment]
This is currently expected behaviour. Values in default cease to matter
once specified in INFILE. But probably this should be revised to allow less
regions than the static constant

**Comment by itamblyn** [comment]
Should we modify the pre processor to put in dummy regions in the generated
yaml file or should this be changed in the main executable?

**Comment by ludamad** [comment]
It should be changed in the code, it shouldn't be any more work than changing the assert and grepping for the uses of the region information vector.

**Comment by ludamad** [comment]
This should now be resolved.
