### ISSUE TITLE
Error with FollowerList upon resubmission

### ISSUE THREAD

**Issue by kryczko** [hashkat/hashkat#73]
In the function action_unfollow in the analyzer_follow, the debug_check function throws an error only after resubmitting a network file.

I have checked the output of the boolean functions in which the debug_check is looking at, and only found one false statement.

After concluding only one false check, I have decided to comment out those debug checks to run simulations (they run as expected).

**Comment by ludamad** [comment]
Please reopen if HEAD does not solve your issue

**Comment by kryczko** [comment]
Is it fixed with the latest commit? What was the solution?
