### ISSUE TITLE
Paper

### ISSUE THREAD

**Issue by itamblyn** [hashkat/hashkat#76]
Paper hasn't been submitted yet...

**Comment by kryczko** [comment]
What needs to be done still?

**Comment by itamblyn** [comment]
:) discussing tomorrow!

- Isaac

**Comment by lkettle** [comment]
Hi,
Q's for tomorrow
- ram consumed by typical simulations
- diagram of a sample path of a favourite tweet.


On Tue, Oct 27, 2015 at 7:31 PM, Isaac Tamblyn <notifications@github.com>
wrote:

> :) discussing tomorrow!
>
> - Isaac
>
> On Tue, Oct 27, 2015 at 7:19 PM, Kevin Ryczko <notifications@github.com>
> wrote:
>
> > What needs to be done still?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/hashkat/hashkat/issues/76#issuecomment-151672916>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hashkat/hashkat/issues/76#issuecomment-151674849>.
>



-- 
Linda Kettle

**Comment by ludamad** [comment]
Issue resolved, thanks @kryczko!
