### ISSUE TITLE
Number of Retweets Not Updating in Output Summary Stats or in 'DATA_vs_TIME' file

### ISSUE THREAD

**Issue by nbuhagiar** [hashkat/hashkat#79]
Though I ran a network simulation with plenty of retweets occurring,

![main_stats_retweets](https://cloud.githubusercontent.com/assets/10453145/10855389/b650be80-7f17-11e5-89d7-134073bda0d5.png)

The number of retweets shown in the output summary stats and in the 'DATA_vs_TIME' file remain at zero.

![summary_output_rate_no_retweets](https://cloud.githubusercontent.com/assets/10453145/10855419/cd6dfb28-7f17-11e5-9498-276d02106b54.png)

**Comment by kryczko** [comment]
It's possible that the stdout did not update before exiting. This is not really a bug, its just the timing of stdout. Try running the simulation for a little bit longer until you see the stdout update, then comment back here.

**Comment by nbuhagiar** [comment]
Hey,

I ran the simulation again for a longer period of time and the number of
retweets in the stdout never seem to show a number greater than 0.

**Comment by lkettle** [comment]
Nick, do you have the INFILE for this?  I want to take a look.

**Comment by nbuhagiar** [comment]
Hey,

This issue has been fixed but I believe it still exists for 'Unfollows',
meaning the number of unfollows that occur in the simulation is not updated
in the output summary stats or in the DATA_vs_TIME file if I remember
correctly.

**Comment by lkettle** [comment]
Closing issue as fixed.
