### ISSUE TITLE
Agent Social Influence

### ISSUE THREAD

**Issue by nbuhagiar** [hashkat/hashkat#85]
Just a request to possibly add a feature in #k@ where an agent's tweet content can be altered based on the tweet content of the agents they are connected with. This can be done to show how an agent is influenced by the other agents they are connected with.

**Comment by itamblyn** [comment]
I think rather than who you are connected to, it might make sense to do it
based on what messages you see. Obviously you'll see more messages from
people that you are connected to, so the effect would still be present, but
focusing on the ideas themselves probably makes more sense.

- Isaac

**Comment by jig08** [comment]
@nbuhagiar @itamblyn Is this the issue related to the concept of `susceptibility` ?

**Comment by itamblyn** [comment]
Yes, this was the initial feature request (so we didn't forget about it!)

**Comment by jig08** [comment]
Oh, You should have let me add the code first  :sweat_drops: 
Anyways, pushing the code ....
