### ISSUE TITLE
'stdout' Update in Real Time Option

### ISSUE THREAD

**Issue by nbuhagiar** [hashkat/hashkat#86]
This is just a request to possibly add an option in #k@ to have the stdout summary update in regular real time intervals. The length of these time intervals can be determined by the #k@ user.

**Comment by itamblyn** [comment]
I don't think the user's need to control this. Let's just go with something
reasonable

**Comment by ludamad** [comment]
It is now implemented. The option changes the meaning of the output rate from simulated to real minutes.
