### ISSUE TITLE
hashkat does not warn user of incorrect Python version / script should be made universal

### ISSUE THREAD

**Issue by lkettle** [hashkat/hashkat#87]
![build_error_nov12](https://cloud.githubusercontent.com/assets/14791604/11134131/7c47c750-8968-11e5-86b1-6979a05c77c4.png)

**Comment by ludamad** [comment]
This error is because you're trying to use hashkat with python 3. Probably we should be very explicit if we detect an incorrect python version.

**Comment by lkettle** [comment]
ok thanks

On Thu, Nov 12, 2015 at 7:46 PM, ludamad <notifications@github.com> wrote:

> This error is because you're trying to use hashkat with python 3. Probably
> we should be very explicit if we detect an incorrect python version.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hashkat/hashkat/issues/87#issuecomment-156282397>.
>



-- 
Linda Kettle

**Comment by ludamad** [comment]
The build and run script now warn if Python 2.x is not used

**Comment by lkettle** [comment]
What is effect of changing "save_file_on_timeout" to false?

Will output still be produced if file stops early?  will output still be
produced when file stops (normally)

What is timeout ?

On Thu, Nov 12, 2015 at 11:06 PM, Linda Kettle <linda.kettle@uoit.net>
wrote:

> ok thanks
>
> On Thu, Nov 12, 2015 at 7:46 PM, ludamad <notifications@github.com> wrote:
>
>> This error is because you're trying to use hashkat with python 3.
>> Probably we should be very explicit if we detect an incorrect python
>> version.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/hashkat/hashkat/issues/87#issuecomment-156282397>.
>>
>
>
>
> --
> Linda Kettle
>



-- 
Linda Kettle

**Comment by lkettle** [comment]
I asked Nick.

On Sat, Nov 14, 2015 at 3:51 PM, Linda Kettle <linda.kettle@uoit.net> wrote:

> What is effect of changing "save_file_on_timeout" to false?
>
> Will output still be produced if file stops early?  will output still be
> produced when file stops (normally)
>
> What is timeout ?
>
> On Thu, Nov 12, 2015 at 11:06 PM, Linda Kettle <linda.kettle@uoit.net>
> wrote:
>
>> ok thanks
>>
>> On Thu, Nov 12, 2015 at 7:46 PM, ludamad <notifications@github.com>
>> wrote:
>>
>>> This error is because you're trying to use hashkat with python 3.
>>> Probably we should be very explicit if we detect an incorrect python
>>> version.
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/hashkat/hashkat/issues/87#issuecomment-156282397>.
>>>
>>
>>
>>
>> --
>> Linda Kettle
>>
>
>
>
> --
> Linda Kettle
>



-- 
Linda Kettle
