### ISSUE TITLE
change default file to match infile yaml

### ISSUE THREAD

**Issue by lkettle** [hashkat/hashkat#88]
right now infile.yaml is changed and default.yaml isn't.  I can copy it over if that is ok.

**Comment by ludamad** [comment]
I have changed the way INFILE.yaml is treated. We should still package INFILE.yaml == DEFAULT.yaml, but now if you do a fresh clone you no longer get an INFILE.yaml. build.sh and run.sh will autogenerate one if they detect one isn't installed. The upside is now everyone can get their local INFILE more easily, and pulling does not affect a user's INFILE.

**Comment by lkettle** [comment]
I'm not sure we're on the same page and I need to understand because it
affects the documentation.

I just did a new clone.  I got a default.yaml but not an infile.yaml.
You're saying infile.yaml will auto generate if missing and if user has a
configured infile, it won't overwrite it.

Q.  So as a starting user if I want to configure infile now I should copy
default.yaml & rename it infile.yaml.

The changes to infile.yaml you made yesterday changed settings on
save_network_on_timeout and load_network_on_startup from true to false.

I submitted #88 because the default.yaml didn't show that change.  It still
doesn't, (see screenshot).

Q.  So when hashkat generates infile.yaml it will pull from default with
those settings set to true.

I'm not sure of all the ramifications from the change in terms of how users
interact with the program.

Speaking with Nick, I understand that users will no longer have to delete
output directory, & DATA_vs_TIME to run a second simulation since they will
simply be over-written.

Q. I am not sure what happens to network_state.dat.  Does it still need to
be removed to run another simulation?

Q. Finally, what happens if user pressed control-C - is their data saved or
aborted?

On Sat, Nov 14, 2015 at 5:23 PM, ludamad <notifications@github.com> wrote:

> Closed #88 <https://github.com/hashkat/hashkat/issues/88>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hashkat/hashkat/issues/88#event-464631469>.
>



-- 
Linda Kettle

**Comment by ludamad** [comment]
All that happens now is that a user does not have an INFILE.yaml until they run build.sh or run.sh, and it has the contents of DEFAULT.yaml. For normal releases, we should provide an INFILE.yaml. This was to stop the constant commits that make small changes in INFILE.yaml for personal testing.

**Comment by lkettle** [comment]
You realize the contents of default are that save_network_on_timeout and
load_network_on_startup are true?

On Sat, Nov 14, 2015 at 9:11 PM, ludamad <notifications@github.com> wrote:

> All that happens now is that a user does not have an INFILE.yaml until
> they run build.sh or run.sh, and it has the contents of DEFAULT.yaml. For
> normal releases, we should provide an INFILE.yaml. This was to stop the
> constant commits that make small changes in INFILE.yaml for personal
> testing.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hashkat/hashkat/issues/88#issuecomment-156770331>.
>



-- 
Linda Kettle

**Comment by ludamad** [comment]
I may have overwritten this by accident, but have no particular preference for the default values.

**Comment by lkettle** [comment]
Ok so just leave them as true in default then none of the documentation needs to be changed.

**Comment by lkettle** [comment]
Ok so if you leave the default as it is, with the items set to TRUE then
none of the documentation needs to be changed.

On Sun, Nov 15, 2015 at 12:53 AM, ludamad <notifications@github.com> wrote:

> I may have overwritten this by accident, but have no particular preference
> for the default values.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hashkat/hashkat/issues/88#issuecomment-156784089>.
>



-- 
Linda Kettle
