### ISSUE TITLE
#k@ Not Able to Fully Build

### ISSUE THREAD

**Issue by nbuhagiar** [hashkat/hashkat#89]
After pulling some of the recent changes made in the repo, #k@ doesn't seem to be able to fully build.

Any idea what could be the cause of this?

**Comment by ludamad** [comment]
Can you attach the build log?

**Comment by nbuhagiar** [comment]
Sure! The error message is super long though.

Here's the beginning:

![build_log_top](https://cloud.githubusercontent.com/assets/10453145/11196538/9eeaf316-8c85-11e5-8c8b-97db4b713799.png)

and end of it:

![build_log_bottom](https://cloud.githubusercontent.com/assets/10453145/11196545/a4d32e42-8c85-11e5-8142-519c099dd6e5.png)

**Comment by nbuhagiar** [comment]
There's more going on in between if you'd like to see all of it

**Comment by ludamad** [comment]
Woops yeah I tried cloning and got the error. I pushed the fix along with a few other fixes
