### ISSUE TITLE
hashkat not Retweeting 

### ISSUE THREAD

**Issue by lkettle** [hashkat/hashkat#92]
hashkat won't generate ANY retweets.

To be sure it wasn't an infile problem I redid the INFILE by copying default, naming it INFILE and making changes.
[INFILE_fail_yaml.txt](https://github.com/hashkat/hashkat/files/82850/INFILE_fail_yaml.txt)

however no retweets are being done.
[DATA_vs_TIME_fail.txt](https://github.com/hashkat/hashkat/files/82852/DATA_vs_TIME_fail.txt)

Yesterday hashkat was doing retweets but it was hit or miss if they made it to retweet_viz.gexf file.  sometime I would get a message like this 
![fail_retweet_viz_gexf](https://cloud.githubusercontent.com/assets/14791604/12201305/907f63da-b5f1-11e5-8b34-a613972775f8.png)  

PS Gephi has upgraded to version 0.9 -> the error message only shows in 0.8 Gephi.

even though the hashkat termination message was successful:

![infile_fail_complete_mess](https://cloud.githubusercontent.com/assets/14791604/12201317/a0201370-b5f1-11e5-8b96-c76ccc48704c.png)

![infile_retry_fail](https://cloud.githubusercontent.com/assets/14791604/12201355/e2266ee0-b5f1-11e5-9a5f-6b7ccf32d7b1.png)

**Comment by lkettle** [comment]
![infile_bil_basic](https://cloud.githubusercontent.com/assets/14791604/12201388/2849e604-b5f2-11e5-9080-ce57afb1bb55.png)
![infile_bil_agents](https://cloud.githubusercontent.com/assets/14791604/12201395/30623bde-b5f2-11e5-98c0-035fa70bf4ac.png)

**Comment by lkettle** [comment]
I had an error in my fixer INFILE.  I revised the INFILE but the problem of no retweets being generated remains. 
![infile_revised_fail](https://cloud.githubusercontent.com/assets/14791604/12202211/a0c588dc-b5f6-11e5-9270-da6c73e88098.png)
[INFILE_revise_yaml.txt](https://github.com/hashkat/hashkat/files/82891/INFILE_revise_yaml.txt)

**Comment by lkettle** [comment]
I rebuilt my INFILE line by line from default, testing after each line changed, and it works now.  

I would note that once INFILE is broken it seems to stay broken and the rebuild has to happen again from scratch.

But closed.

**Comment by itamblyn** [comment]
What editor are you using?

**Comment by lkettle** [comment]
The break happens here, when I change the weights of the ideologies.
Working is on left, Broken is on right.  All other code equal.
![working_broken](https://cloud.githubusercontent.com/assets/14791604/12213188/434441fc-b642-11e5-888a-2f73c8967ccc.png)

I was using markdown.  I thought that might be it, and switched to nano but nano doesn't allow cut and paste.  Anyway, I've done about 100 runs today and markdown didn't make a difference.  The break happens where indicated above.  

After you change the ideologies, you no longer get any retweeting.   Most popular tweet content doesn't fill in.

**Comment by lkettle** [comment]
mousepad

**Comment by lkettle** [comment]
Ok so I tested this again this morning because WHY should region ideology weights affect retweeting?  that said, the problem comes here.  When the region has only one ideology, there are no retweets.
My standard agent has "care about ideology FALSE" btw

this works 100 100 100 100
![infile_working_ideology_4x100](https://cloud.githubusercontent.com/assets/14791604/12217563/648b816e-b6d2-11e5-9fc5-d4f99e020364.png)

this works 90 10 0 0
![infile_working_ideology_90_10_0_0](https://cloud.githubusercontent.com/assets/14791604/12217565/76ca28a8-b6d2-11e5-8c71-5cec95ad037c.png)

this does NOT work (no retweets generated) 100 0 0 0
![infile_not_working_ideology_0_100_0_0](https://cloud.githubusercontent.com/assets/14791604/12217570/8564a1f4-b6d2-11e5-8b54-c55153b7a26a.png)

I have all the output files plus network state & DATA v TIME for each.  They are all starting with the same seed 1.

**Comment by lkettle** [comment]
The working files were created FROM the broken file and then from working I broke it again, all with the ideology weights ALONE being the only change, so it is not an editor issue.

**Comment by itamblyn** [comment]
@kryczko Can you have a look at this please.

**Comment by kryczko** [comment]
Linda, can you please send me the INFILE.yaml file you are using.

**Comment by kryczko** [comment]
i just ran a similar config to what you have and I did not have a problem. Retweets occurred for me.

**Comment by lkettle** [comment]
this is the infile that is broken

On Sat, Jan 9, 2016 at 3:18 PM, Kevin Ryczko <notifications@github.com>
wrote:

> i just ran a similar config to what you have and I did not have a problem.
> Retweets occurred for me.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hashkat/hashkat/issues/92#issuecomment-170277988>.
>



-- 
Linda Kettle

**Comment by lkettle** [comment]
Better copies.  The broken one doesn't retweet.

On Sat, Jan 9, 2016 at 4:27 PM, Linda Kettle <linda.kettle@uoit.net> wrote:

> this is the infile that is broken
>
> On Sat, Jan 9, 2016 at 3:18 PM, Kevin Ryczko <notifications@github.com>
> wrote:
>
>> i just ran a similar config to what you have and I did not have a
>> problem. Retweets occurred for me.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/hashkat/hashkat/issues/92#issuecomment-170277988>.
>>
>
>
>
> --
> Linda Kettle
>



-- 
Linda Kettle

**Comment by kryczko** [comment]
Can you please show me the main_stats.dat for both simulations.

**Comment by lkettle** [comment]
thanks, I appreciate your help.  I did my datasets with a 90-10 ideology
configuration, which runs.

On Sat, Jan 9, 2016 at 4:40 PM, Kevin Ryczko <notifications@github.com>
wrote:

> Can you please show me the main_stats.dat for both simulations.
> > On Jan 9, 2016, at 4:27 PM, lkettle <notifications@github.com> wrote:
> >
> > this is the infile that is broken
> >
> > On Sat, Jan 9, 2016 at 3:18 PM, Kevin Ryczko <notifications@github.com>
> > wrote:
> >
> > > i just ran a similar config to what you have and I did not have a
> problem.
> > > Retweets occurred for me.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/hashkat/hashkat/issues/92#issuecomment-170277988>.
> > >
> >
> >
> >
> > --
> > Linda Kettle
> > —
> > Reply to this email directly or view it on GitHub <
> https://github.com/hashkat/hashkat/issues/92#issuecomment-170283646>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hashkat/hashkat/issues/92#issuecomment-170284351>.
>



-- 
Linda Kettle

**Comment by kryczko** [comment]
The logic is fine, there is a retweet rate that is non-zero in the total rate for the system. I noticed that the average number of followers is very low (1.02). This means that even if we land on retweeting, we will not. Please adjust the rates to have more average followers and post here if the problem still occurs. I will close once this is confirmed.

**Comment by itamblyn** [comment]
@linda Please add this to the troubleshooting section. I can see other
users having similar problems!!

- Isaac

**Comment by lkettle** [comment]
Which rate should I adjust?

**Comment by lkettle** [comment]
So if it's a "it's happenning you just need to have sex more" argument re
getting pregnant, if I run simulation longer I should get retweets?

The current follow rate for standards is system default.

Why should it matter if 90% red 10% blue vs 100% red 0% blue if Standard
agents (100/101 of population) don't care about ideology?  The number of
agents of each ideology in the system should be equal in both scenarios.

In my simulation only celebrities care about ideology in retweets.
Although celebrities are followed 10x more than standards.

I will play with numbers & rates & see.

**Comment by lkettle** [comment]
When I look at main_stats.dat for the 100-0 ideology split, I see 0
retweets,
whereas in the same file (same seed, different ideology mix 90-10) there
are 37,000 retweets.

In both cases, standard agents (who don't care about ideology) are 91% of
total agent population.
there are 23000 agents and 126000 follows (so 1:5 agent follower)

I mean, I don't understand where you are getting the retweet rate non zero
and the 1.02 follow rate.

Not trying to argue, trying to understand.

On Sat, Jan 9, 2016 at 4:54 PM, Kevin Ryczko <notifications@github.com>
wrote:

> The logic is fine, there is a retweet rate that is non-zero in the total
> rate for the system. I noticed that the average number of followers is very
> low (1.02). This means that even if we land on retweeting, we will not.
> Please adjust the rates to have more average followers and post here if the
> problem still occurs. I will close once this is confirmed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hashkat/hashkat/issues/92#issuecomment-170285619>.
>



-- 
Linda Kettle

**Comment by kryczko** [comment]
A 1:5 follower is still very low. If you take 5 * 0.07 you get the transmission rate which is very low. This means the agents would need to tweet many many times before being retweeted. The problem in the simulations is this. Decrease the add rate and increase the follow and tweet rates and you should see retweets occur.

Kevin

**Comment by lkettle** [comment]
I took Tutorial 13's INFILE, modified it a bit, and ran it with a 90-10-0-0 ideology weight which generated 8600 retweets, and then I changed it to a 100-0-0-0 ideology weight and got 0 retweets.

MAIN_STATS.dat working on left, broken on right.
![main_stats_compare](https://cloud.githubusercontent.com/assets/14791604/12219805/3b7d359e-b720-11e5-84d6-20e37cc3193e.png)

INFILE working on left, broken on right
![infile_13_broken](https://cloud.githubusercontent.com/assets/14791604/12219808/4c6aa4c2-b720-11e5-89a2-2480d0288000.png)

**Comment by lkettle** [comment]
This simulation had a zero add rate.

**Comment by lkettle** [comment]
This simulation had a zero add rate for agents.

**Comment by lkettle** [comment]
![standard_pref](https://cloud.githubusercontent.com/assets/14791604/12219828/2ea83264-b721-11e5-8fab-8201ab53fc67.png)

**Comment by lkettle** [comment]
Agent types standard, organization-1, organization 2.

**Comment by lkettle** [comment]
I tried an INFILE from tutorial 13 (with modifications) and I "broke" it
too by setting region ideology weight to 100-0

do you have a favourite infile you can test by changing Ideology
configuration to 100% - 0 0 0 ?

If you have an INFILE that works with that configuration, can you send a
copy to me?

Thanks,

Linda
(I know it's Saturday night)

On Sat, Jan 9, 2016 at 9:05 PM, Kevin Ryczko <notifications@github.com>
wrote:

> A 1:5 follower is still very low. If you take 5 * 0.07 you get the
> transmission rate which is very low. This means the agents would need to
> tweet many many times before being retweeted. The problem in the
> simulations is this. Decrease the add rate and increase the follow and
> tweet rates and you should see retweets occur.
>
> Kevin
>
> > On Jan 9, 2016, at 8:59 PM, lkettle <notifications@github.com> wrote:
> >
> > When I look at main_stats.dat for the 100-0 ideology split, I see 0
> > retweets,
> > whereas in the same file (same seed, different ideology mix 90-10) there
> > are 37,000 retweets.
> >
> > In both cases, standard agents (who don't care about ideology) are 91% of
> > total agent population.
> > there are 23000 agents and 126000 follows (so 1:5 agent follower)
> >
> > I mean, I don't understand where you are getting the retweet rate non
> zero
> > and the 1.02 follow rate.
> >
> > Not trying to argue, trying to understand.
> >
> > On Sat, Jan 9, 2016 at 4:54 PM, Kevin Ryczko <notifications@github.com>
> > wrote:
> >
> > > The logic is fine, there is a retweet rate that is non-zero in the
> total
> > > rate for the system. I noticed that the average number of followers is
> very
> > > low (1.02). This means that even if we land on retweeting, we will not.
> > > Please adjust the rates to have more average followers and post here
> if the
> > > problem still occurs. I will close once this is confirmed.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/hashkat/hashkat/issues/92#issuecomment-170285619>.
> > >
> >
> >
> >
> > --
> > Linda Kettle
>
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hashkat/hashkat/issues/92#issuecomment-170300558>.
>



-- 
Linda Kettle

**Comment by kryczko** [comment]
please email me the exact INFILE.yaml

**Comment by lkettle** [comment]
It's sat night, it can wait to tomorrow!  but here's data

On Sat, Jan 9, 2016 at 10:55 PM, Kevin Ryczko <notifications@github.com>
wrote:

> please email me the exact INFILE.yaml
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hashkat/hashkat/issues/92#issuecomment-170308376>.
>



-- 
Linda Kettle

**Comment by kryczko** [comment]
I ran the INFILE.yaml, and recovered the problem. The logic seems OK, I think there is a bug here. The regions would be separated completely due to languages being completely different. This means that retweeting should only occur within the same regions, but the bug happens when there is only one ideology. @ludamad could you have a look at this.
[INFILE.yaml.zip](https://github.com/hashkat/hashkat/files/85118/INFILE.yaml.zip)

**Comment by lkettle** [comment]
This is a NEW problem with RETWEET generator - unrelated to IDEOLOGY, now related to LANGUAGE.

Specifically if ** first** region** first** language is **zero** no retweets are generated.
(previously if first region first ideology was zero no retweets were generated).

Text compare of the INFILES, the one on the right works, and the one on the left doesn't.  Language weight is the only differences between the files.

![weirdness_retweets](https://cloud.githubusercontent.com/assets/14791604/12692657/40c1b9dc-c6c8-11e5-8581-5176e2a23092.png)

![retweet_datavtime](https://cloud.githubusercontent.com/assets/14791604/12692658/4d6b32d0-c6c8-11e5-8b5b-852decc8b173.png)

[INFILE_working.yaml.zip](https://github.com/hashkat/hashkat/files/110616/INFILE_working.yaml.zip)
[INFILE_not_working_2.yaml.zip](https://github.com/hashkat/hashkat/files/110617/INFILE_not_working_2.yaml.zip)

**Comment by lkettle** [comment]
also, although the data should be equal but reflected, one file took 1500 lines longer to run.

**Comment by kryczko** [comment]
I looked to see how the configure file is being parsed and everything was fine there. It seems to be a problem with the the retweet structure. @domurad if you see this can you please investigate.

**Comment by kryczko** [comment]
Whupps I meant @ludamad can you please investigate.

**Comment by lkettle** [comment]
This problem still exists:  if Ideology(0) is 0% then there is no retweeting.  (one region world).
![no-retweet-0red_id](https://cloud.githubusercontent.com/assets/14791604/12899041/912db9d6-ce7d-11e5-9d96-747cfc02dc42.png)

**Comment by lkettle** [comment]
Also if red - ideology (0) is **0%** in world (any number of regions red = 0%) then no RETWEETS occur.

**Comment by lkettle** [comment]
To recreate this ideology bug, take any INFILE you want - including DEFAULT.
Change red ideology_weight to 0 in all regions that have a positive add_weight.
./run.sh
